/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6_carlosfortin_11911015;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.InputMismatchException;
import java.util.Scanner;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Carlos Fortin
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        try {
            initComponents();
            this.setExtendedState(MAXIMIZED_BOTH);
            leerInventario();
            System.out.println(inventario);
            actualizarTabla();
            leerNoFact();
        } catch (ParseException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregarproducto = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ff_codigo = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tf_marca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tf_azucar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_alcohol = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cb_nacional = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        tf_colorantes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_precio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        sp_cantidad = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        dc_vencimiento = new com.toedter.calendar.JDateChooser();
        jb_agregar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        tf_lote = new javax.swing.JTextField();
        jd_modificarproducto = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        ff_modcod = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        tf_modmarca = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        tf_modnombre = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        tf_modcantaz = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        tf_modcantal = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        cb_modnacional = new javax.swing.JComboBox<>();
        jButton9 = new javax.swing.JButton();
        tf_modlote = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        tf_modprecio = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        sp_modcant = new javax.swing.JSpinner();
        jButton12 = new javax.swing.JButton();
        dc_modvencimiento = new com.toedter.calendar.JDateChooser();
        jButton13 = new javax.swing.JButton();
        tf_modcolor = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jd_cotizacion = new javax.swing.JDialog();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabla_cot = new javax.swing.JTable();
        jButton14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_inventario = new javax.swing.JTable();
        jb_agregarprod = new javax.swing.JButton();
        jb_modprod = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setText("Agregar Bebida");

        jLabel3.setText("Codigo");

        try {
            ff_codigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Marca");

        jLabel5.setText("Nombre Producto");

        jLabel6.setText("Cantidad de Azucar");

        jLabel7.setText("Cantidad de Alcohol");

        jLabel8.setText("Producto nacional");

        cb_nacional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jLabel9.setText("Colorantes");

        jLabel10.setText("En caso de que tenga mas de un colorante por favor ingresarlo como");

        jLabel11.setText("Colorante1,Colorante2,...etc");

        jLabel12.setText("Precio");

        jLabel13.setText("Cantidad");

        sp_cantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel14.setText("Fecha de Vencimiento");

        jb_agregar.setText("Agregar");
        jb_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarMouseClicked(evt);
            }
        });

        jLabel15.setText("No. Lote");

        javax.swing.GroupLayout jd_agregarproductoLayout = new javax.swing.GroupLayout(jd_agregarproducto.getContentPane());
        jd_agregarproducto.getContentPane().setLayout(jd_agregarproductoLayout);
        jd_agregarproductoLayout.setHorizontalGroup(
            jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(cb_nacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_alcohol))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_azucar, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(ff_codigo))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(tf_colorantes)))
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarproductoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jb_agregar)
                                .addGap(107, 107, 107))
                            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                .addGap(116, 116, 116)
                                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_lote))
                                    .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dc_vencimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addComponent(jLabel11))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_agregarproductoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(305, 305, 305))
        );
        jd_agregarproductoLayout.setVerticalGroup(
            jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(53, 53, 53)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ff_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(tf_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(sp_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_agregarproductoLayout.createSequentialGroup()
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(26, 26, 26)
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(tf_azucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(tf_lote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tf_alcohol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(cb_nacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_agregar))
                        .addGap(18, 18, 18)
                        .addGroup(jd_agregarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(tf_colorantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dc_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setText("Modificar");

        try {
            ff_modcod.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton4.setText("Modificar codigo");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Modificar marca");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setText("Modificar nombre");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setText("Modificar cantidad azucar");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setText("Modificar cantidad alcohol");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        cb_modnacional.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Si", "No" }));

        jButton9.setText("Modificar nacionalidad");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setText("Modificar lote");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setText("Modificar precio");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        sp_modcant.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jButton12.setText("Modifficar cantidad");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        jButton13.setText("Modificar Vencimiento");
        jButton13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton13MouseClicked(evt);
            }
        });

        jButton15.setText("Modificar Colorantes");
        jButton15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton15MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_modificarproductoLayout = new javax.swing.GroupLayout(jd_modificarproducto.getContentPane());
        jd_modificarproducto.getContentPane().setLayout(jd_modificarproductoLayout);
        jd_modificarproductoLayout.setHorizontalGroup(
            jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                .addGap(459, 459, 459)
                .addComponent(jLabel16)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarproductoLayout.createSequentialGroup()
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jButton4))
                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jButton5)))
                        .addGap(124, 124, 124)
                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 536, Short.MAX_VALUE))
                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                .addComponent(jButton7)
                                .addGap(144, 144, 144)
                                .addComponent(jButton10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton13))))
                    .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6)
                            .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ff_modcod, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                .addComponent(tf_modmarca)
                                .addComponent(tf_modnombre)))
                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(cb_modnacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(263, 263, 263)
                                .addComponent(sp_modcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modificarproductoLayout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(jButton9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton12))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_modificarproductoLayout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton11)
                                            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                                                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_modcantaz, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_modcantal, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(148, 148, 148)
                                                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tf_modlote, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tf_modprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dc_modvencimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_modificarproductoLayout.createSequentialGroup()
                                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButton15)
                                            .addComponent(tf_modcolor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)))))))
                .addGap(27, 27, 27))
        );
        jd_modificarproductoLayout.setVerticalGroup(
            jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel16)
                .addGap(31, 31, 31)
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ff_modcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_modcantaz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf_modlote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dc_modvencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton7)
                            .addComponent(jButton10)))
                    .addGroup(jd_modificarproductoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButton13)))
                .addGap(32, 32, 32)
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_modmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_modcantal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_modprecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_modcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton8)
                    .addComponent(jButton11)
                    .addComponent(jButton15))
                .addGap(27, 27, 27)
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_modnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_modnacional, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sp_modcant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_modificarproductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton9)
                    .addComponent(jButton12))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel17.setText("Cotizacion");

        Tabla_cot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(Tabla_cot);

        jButton14.setText("Imprimir cotizacion");
        jButton14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton14MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_cotizacionLayout = new javax.swing.GroupLayout(jd_cotizacion.getContentPane());
        jd_cotizacion.getContentPane().setLayout(jd_cotizacionLayout);
        jd_cotizacionLayout.setHorizontalGroup(
            jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cotizacionLayout.createSequentialGroup()
                .addGroup(jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_cotizacionLayout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel17))
                    .addGroup(jd_cotizacionLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_cotizacionLayout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jButton14)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        jd_cotizacionLayout.setVerticalGroup(
            jd_cotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_cotizacionLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel17)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton14)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Supermercado El Barrio");

        Tabla_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Nombre", "Cant. Azucar", "Cant. Alcohol", "Nacional", "No. Lote", "Precio", "Cantidad", "Vence", "Colorantes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabla_inventario);

        jb_agregarprod.setText("Agregar Producto");
        jb_agregarprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregarprodMouseClicked(evt);
            }
        });

        jb_modprod.setText("Modificar producto");
        jb_modprod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modprodMouseClicked(evt);
            }
        });

        jButton1.setText("Agregar a Cotizacion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Ver productos cotizados");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Eliminar producto");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(501, 501, 501)
                .addComponent(jLabel1)
                .addGap(32, 32, 32))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jb_agregarprod)
                        .addGap(350, 350, 350)
                        .addComponent(jb_modprod)
                        .addGap(392, 392, 392)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_modprod)
                    .addComponent(jb_agregarprod)
                    .addComponent(jButton3))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_agregarprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarprodMouseClicked
        jd_agregarproducto.setVisible(true);
        //jd_agregarproducto.setModal(true);
        jd_agregarproducto.pack();
        jd_agregarproducto.setLocationRelativeTo(this);
    }//GEN-LAST:event_jb_agregarprodMouseClicked

    private void jb_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregarMouseClicked
        if(ff_codigo.getText().isEmpty() || tf_marca.getText().isEmpty() || tf_nombre.getText().isEmpty() || tf_precio.getText().isEmpty())
            JOptionPane.showMessageDialog(jd_agregarproducto,"No se puede agregar producto");
        else{
            try{
                int c=Integer.parseInt(ff_codigo.getText());
                String nm=tf_marca.getText();
                String n=tf_nombre.getText();
                double a=Double.parseDouble(tf_azucar.getText());
                double al=Double.parseDouble(tf_alcohol.getText());
                boolean x;
                if(cb_nacional.getSelectedItem().toString()=="Si")
                    x=true;
                else
                    x=false;
                int lote=Integer.parseInt(tf_lote.getText());
                String colorantes=tf_colorantes.getText();
                double precio=Double.parseDouble(tf_precio.getText());
                int cantidad=Integer.parseInt(sp_cantidad.getValue().toString());
                SimpleDateFormat d=new SimpleDateFormat("dd/MM/yyyy");
                String vencimiento=d.format(dc_vencimiento.getDate()).toString();

                if(inventario.size()>0){
                    for (Bebida b : inventario) {
                        if(b.getCodigo()==c)
                            JOptionPane.showMessageDialog(jd_agregarproducto,"No puede haber dos productos con el mismo codigo");
                        else{
                            inventario.add(new Bebida(c, nm, n, a, al, x, lote, precio, cantidad, vencimiento,colorantes));
                            actualizarTabla();
                            escribir();
                        }
                    }
                }
                else{
                   inventario.add(new Bebida(c, nm, n, a, al, x, lote, precio, cantidad, vencimiento,colorantes));
                   escribir();
                   actualizarTabla(); 
                }
            }catch(Exception e){
                
            }
        }
        
        ff_codigo.setText("");
        tf_marca.setText("");
        tf_nombre.setText("");
        tf_azucar.setText("");
        tf_alcohol.setText("");
        cb_nacional.setSelectedIndex(0);
        tf_lote.setText("");
        tf_colorantes.setText("");
        tf_precio.setText("");
        sp_cantidad.setValue(0);
        dc_vencimiento.setDate(null);
        
    }//GEN-LAST:event_jb_agregarMouseClicked

    private void jb_modprodMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modprodMouseClicked
        //Bebida temp;
        if(Tabla_inventario.getSelectedRow()>=0){
            jd_modificarproducto.setVisible(true);
            jd_modificarproducto.pack();
            for (Bebida bebida : inventario) {
                if(Tabla_inventario.getValueAt(Tabla_inventario.getSelectedRow(), 0).equals(bebida.getCodigo())){
                    temp=bebida;
                    break;
                }
            }
            System.out.println(temp);
        }
    }//GEN-LAST:event_jb_modprodMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        try {
            temp.setCodigo(Integer.parseInt(ff_modcod.getText()));
            ff_modcod.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        try {
            temp.setNombre_marca(tf_modmarca.getText());
            tf_modmarca.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try {
            temp.setNombre_bebida(tf_modnombre.getText());
            tf_modnombre.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        try {
            temp.setCant_azucar(Double.parseDouble(tf_modcantaz.getText()));
            tf_modcantaz.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        try {
            temp.setCant_alcohol(Double.parseDouble(tf_modcantal.getText()));
            tf_modcantal.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        try {
            if(cb_modnacional.getSelectedItem().toString().equals("Si"))
                temp.setNacional(true);
            else
                temp.setNacional(false);
            escribir();
            actualizarTabla();
            
            cb_modnacional.setSelectedIndex(0);
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        try {
            temp.setNo_lote(Integer.parseInt(tf_modlote.getText()));
            tf_modlote.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        try {
            temp.setPrecio(Double.parseDouble(tf_modprecio.getText()));
            tf_modprecio.setText("");
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        temp.setCantidad(Integer.parseInt(sp_modcant.getValue().toString()));
        sp_modcant.setValue(0);
        temp=null;
        try {
            escribir();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualizarTabla();
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton13MouseClicked
        try {
            SimpleDateFormat d=new SimpleDateFormat("dd/MM/yyyy");
            String vencimiento=d.format(dc_modvencimiento.getDate()).toString();
            temp.setFecha_vencimiento(vencimiento);
            dc_modvencimiento.setDate(null);
            escribir();
            actualizarTabla();
            temp=null;
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        if(Tabla_inventario.getSelectedRow()>=0){
            try {
                for (Bebida bebida : inventario) {
                    if(Tabla_inventario.getValueAt(Tabla_inventario.getSelectedRow(), 0).equals(bebida.getCodigo())){
                        inventario.remove(bebida);
                        break;
                    }
                }
                escribir();
                actualizarTabla();
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if(Tabla_inventario.getSelectedRow()>=0){
                for (Bebida bebida : inventario) {
                    if(Tabla_inventario.getValueAt(Tabla_inventario.getSelectedRow(), 0).equals(bebida.getCodigo())){
                        cotizados.add(bebida);
                        int cantidad=Integer.parseInt(JOptionPane.showInputDialog("Cantidad"));
                        cotizados.get(cotizados.size()-1).setCantidad(cantidad);
                        System.out.println(cotizados);
                        actualizarCot();
                        break;
                    }
                }
            
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_cotizacion.setVisible(true);
        jd_cotizacion.pack();
        jd_cotizacion.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton14MouseClicked
        try {                                       
            FileWriter fw=null;
            BufferedWriter bw=null;
            try {
                File factura=new File("./Cotizaciones/Cotizacion"+no_fact+".txt");
                double total=0;
                fw=new FileWriter(factura,false);
                bw=new BufferedWriter(fw);
                bw.write("Supermercado El Barrio"+"\n\n");
                bw.write("Factura#"+no_fact+"                   "+new Date()+"\n\n");
                bw.write("Nombre"+"            "+"Cantidad"+"          "+"Precio"+"\n\n");
                for (Bebida b : cotizados) {
                    bw.write(b.getNombre_bebida()+"                  "+b.getCantidad()+"               "+b.getPrecio()+"\n\n\n");
                    total+=b.getPrecio()*b.getCantidad();
                }
                bw.write("                                                    Total: "+total);
                bw.flush();
                total=0;
            } catch (Exception e) {
            }
            bw.close();
            fw.close();
            no_fact++;
            actualizarNoFact();
            cotizados=new ArrayList();
                Tabla_cot.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "Producto", "Cantidad", "Precio"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
                };
                boolean[] canEdit = new boolean [] {
                    false, false, false
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }

                public boolean isCellEditable(int rowIndex, int columnIndex) {
                    return canEdit [columnIndex];
                }
            });
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14MouseClicked

    private void jButton15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton15MouseClicked
        temp.getColorantes().clear();
        temp.setColorantes(tf_modcolor.getText());
        tf_modcolor.setText("");
        temp=null;
        try {
            escribir();
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        actualizarTabla();
    }//GEN-LAST:event_jButton15MouseClicked

    public void actualizarNoFact() throws IOException{
        File numero=new File("./Cotizaciones/numero_factura.txt");
        FileWriter fw=null;
        BufferedWriter bw=null;
        try {
            fw=new FileWriter(numero,false);
            bw=new BufferedWriter(fw);
            bw.write(Integer.toString(no_fact));
        } catch (Exception e) {
        }
        bw.close();
        fw.close();
    }
    
    public void leerNoFact() throws FileNotFoundException{
        File numero=new File("./Cotizaciones/numero_factura.txt");
        if(numero.exists()){
            Scanner leer=new Scanner(numero);
            no_fact=leer.nextInt();
        }
    }
    
    public void escribir() throws IOException{
        FileWriter fw=null;
        BufferedWriter bw=null;
        try {
            fw=new FileWriter(archivo,false);
            bw=new BufferedWriter(fw);
            for (Bebida b : inventario) {
                bw.write(b.getCodigo()+";");
                bw.write(b.getNombre_marca()+";");
                bw.write(b.getNombre_bebida()+";");
                bw.write(b.getCant_azucar()+";");
                bw.write(b.getCant_alcohol()+";");
                bw.write(b.isNacional()+";");
                bw.write(b.getNo_lote()+";");
                bw.write(b.getPrecio()+";");
                bw.write(b.getCantidad()+";");
                bw.write(b.getFecha_vencimiento().toString()+";");
                bw.write(b.getColoresS()+";"+"\n");
            }
            bw.flush();
        } catch (Exception e) {
        }
        bw.close();
        fw.close();
    }
    //inventario.add(new Bebida((Integer)tokens[0],(String)tokens[1],(String)tokens[2],(Double)tokens[3],(Double)tokens[4],(Boolean)tokens[5],(Integer)tokens[6],(Double)tokens[7],(Integer)tokens[8],(String)tokens[9],(String)tokens[10]));
    public void leerInventario() throws FileNotFoundException, ParseException, IOException{
        
        FileReader fr=null;
        BufferedReader br=null;
        try {
            fr=new FileReader(archivo);
            br=new BufferedReader(fr);
            String linea;
            while((linea=br.readLine())!=null){
                Object[] tokens=linea.split(";");
                inventario.add(new Bebida(Integer.parseInt(tokens[0].toString()),(String)tokens[1],(String)tokens[2],Double.parseDouble(tokens[3].toString()),Double.parseDouble(tokens[4].toString()),Boolean.parseBoolean(tokens[5].toString()),Integer.parseInt(tokens[6].toString()),Double.parseDouble(tokens[7].toString()),Integer.parseInt(tokens[8].toString()),(String)tokens[9],(String)tokens[10]));
            }
        } catch (NullPointerException e) {
        }
        br.close();
        fr.close();
        
    }
    
    public void actualizarTabla(){
        Tabla_inventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Marca", "Nombre", "Cant. Azucar", "Cant. Alcohol", "Nacional", "No. Lote", "Precio", "Cantidad", "Vence", "Colorantes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel modelo=(DefaultTableModel)Tabla_inventario.getModel();
        for (Bebida b : inventario) {
            Object[] inven={b.getCodigo(),b.getNombre_marca(),b.getNombre_bebida(),b.getCant_azucar(),b.getCant_alcohol(),b.isNacional(),b.getNo_lote(),b.getPrecio(),b.getCantidad(),b.getFecha_vencimiento(),b.getColoresS()};
            modelo.addRow(inven);
        }
        System.out.println(inventario);
        Tabla_inventario.setModel(modelo);
    }
    
    public void actualizarCot(){
        Tabla_cot.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        
        DefaultTableModel modelo=(DefaultTableModel)Tabla_cot.getModel();
        for (Bebida b : cotizados) {
            Object[] inven={b.getNombre_bebida(),b.getCantidad(),(b.getPrecio()*b.getCantidad())};
            modelo.addRow(inven);
        }
        Tabla_cot.setModel(modelo);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla_cot;
    private javax.swing.JTable Tabla_inventario;
    private javax.swing.JComboBox<String> cb_modnacional;
    private javax.swing.JComboBox<String> cb_nacional;
    private com.toedter.calendar.JDateChooser dc_modvencimiento;
    private com.toedter.calendar.JDateChooser dc_vencimiento;
    private javax.swing.JFormattedTextField ff_codigo;
    private javax.swing.JFormattedTextField ff_modcod;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_agregar;
    private javax.swing.JButton jb_agregarprod;
    private javax.swing.JButton jb_modprod;
    private javax.swing.JDialog jd_agregarproducto;
    private javax.swing.JDialog jd_cotizacion;
    private javax.swing.JDialog jd_modificarproducto;
    private javax.swing.JSpinner sp_cantidad;
    private javax.swing.JSpinner sp_modcant;
    private javax.swing.JTextField tf_alcohol;
    private javax.swing.JTextField tf_azucar;
    private javax.swing.JTextField tf_colorantes;
    private javax.swing.JTextField tf_lote;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_modcantal;
    private javax.swing.JTextField tf_modcantaz;
    private javax.swing.JTextField tf_modcolor;
    private javax.swing.JTextField tf_modlote;
    private javax.swing.JTextField tf_modmarca;
    private javax.swing.JTextField tf_modnombre;
    private javax.swing.JTextField tf_modprecio;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_precio;
    // End of variables declaration//GEN-END:variables
    ArrayList<Bebida> inventario=new ArrayList();
    ArrayList<Bebida> cotizados=new ArrayList();
    File archivo=new File("./bebidas.txt");
    Bebida temp;
    int no_fact=0;
}
